In [11]:
import pandas as pd
import glob
import json
import numpy as np
import pandas as pd

In [12]:

files = glob.glob('data/tweet_usmnt/*')
#files = glob.glob('user/*')
len(files)

40812

In [13]:
dictlist = []

for file in files:
    json_string = open(file, 'r').read()
    json_dict = json.loads(json_string)
    dictlist.append(json_dict)

In [14]:

df = pd.DataFrame(dictlist)

df = df.replace({'\n': ' '}, regex=True) # remove linebreaks in the dataframe
df = df.replace({'\t': ' '}, regex=True) # remove tabs in the dataframe
df = df.replace({'\r': ' '}, regex=True) # remove carriage return in the dataframe
df.rename(columns={'text':'tweet', 'compound':'compound_score'}, inplace=True)
df.head()

,ID,datetime,has_media,is_reply,is_retweet,medias,nbr_favorite,nbr_reply,nbr_retweet,tweet,url,user_id,usernameTweet
0,1142610007541915648,2019-06-22 21:47:09,NaN,False,False,NaN,4,1,0,The US men are playing like women tonight! Can...,/LeBradyJames/status/1142610007541915648,282399290,LeBradyJames
1,1142610008468860929,2019-06-22 21:47:09,NaN,False,False,NaN,0,0,0,Cannon on for Lima. #USMNT,/UncSamSoccerPod/status/1142610008468860929,877049725958193152,UncSamSoccerPod
2,1142610009915908097,2019-06-22 21:47:09,NaN,True,False,NaN,0,1,0,Remember when people were freaking out about u...,/TUpdike15/status/1142610009915908097,424775138,TUpdike15
3,1142610014005157888,2019-06-22 21:47:10,NaN,True,False,NaN,4,0,1,Where was this during world cup qualifications?,/hongtkwan/status/1142610014005157888,2302603976,hongtkwan
4,1142610014412185600,2019-06-22 21:47:10,NaN,True,False,NaN,34,1,1,There is never an excuse for any USMNT to ev...,/ussoccerfeed/status/1142610014412185600,2551822934,ussoccerfeed

In [15]:
import re
def process_tweet(tweet):
    return " ".join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])", "",tweet.lower()).split())

In [16]:
#initialize the Vader library

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyser = SentimentIntensityAnalyzer()

In [17]:
#create the analyzer function

def sentiment_analyzer_scores(sentence):
    score = analyser.polarity_scores(sentence)
    print("{:-<40} {}".format(sentence, str(score)))

In [18]:
#test the analyzer using a random sentence we input

sentiment_analyzer_scores("The phone is super cool.")

The phone is super cool.---------------- {'neg': 0.0, 'neu': 0.326, 'pos': 0.674, 'compound': 0.7351}

In [19]:
sentiment_analyzer_scores("You can't win a championship without gays on your team. It has never been done before. Ever. That's science right there.")

You can't win a championship without gays on your team. It has never been done before. Ever. That's science right there. {'neg': 0.233, 'neu': 0.767, 'pos': 0.0, 'compound': -0.6681}

In [20]:
sid = SentimentIntensityAnalyzer()


listy = []

for index, row in df.iterrows():
  ss = sid.polarity_scores(row["tweet"])
  listy.append(ss)

se = pd.Series(listy)
df['polarity'] = se.values

display(df.head(10))

,ID,datetime,has_media,is_reply,is_retweet,medias,nbr_favorite,nbr_reply,nbr_retweet,tweet,url,user_id,usernameTweet,polarity
0,1142610007541915648,2019-06-22 21:47:09,NaN,False,False,NaN,4,1,0,The US men are playing like women tonight! Can...,/LeBradyJames/status/1142610007541915648,282399290,LeBradyJames,"{'neg': 0.0, 'neu': 0.731, 'pos': 0.269, 'comp..."
1,1142610008468860929,2019-06-22 21:47:09,NaN,False,False,NaN,0,0,0,Cannon on for Lima. #USMNT,/UncSamSoccerPod/status/1142610008468860929,877049725958193152,UncSamSoccerPod,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
2,1142610009915908097,2019-06-22 21:47:09,NaN,True,False,NaN,0,1,0,Remember when people were freaking out about u...,/TUpdike15/status/1142610009915908097,424775138,TUpdike15,"{'neg': 0.291, 'neu': 0.596, 'pos': 0.112, 'co..."
3,1142610014005157888,2019-06-22 21:47:10,NaN,True,False,NaN,4,0,1,Where was this during world cup qualifications?,/hongtkwan/status/1142610014005157888,2302603976,hongtkwan,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
4,1142610014412185600,2019-06-22 21:47:10,NaN,True,False,NaN,34,1,1,There is never an excuse for any USMNT to ev...,/ussoccerfeed/status/1142610014412185600,2551822934,ussoccerfeed,"{'neg': 0.067, 'neu': 0.933, 'pos': 0.0, 'comp..."
5,1142610016760823808,2019-06-22 21:47:11,NaN,True,False,NaN,1,0,0,"Now were rolling, hope this game shuts up all ...",/sd_packattack/status/1142610016760823808,1896009180,sd_packattack,"{'neg': 0.177, 'neu': 0.663, 'pos': 0.16, 'com..."
6,1142610018006704134,2019-06-22 21:47:11,NaN,True,False,NaN,0,0,0,First team that shuts Pullisic down we are doo...,/Roberto61617837/status/1142610018006704134,1016991174253580290,Roberto61617837,"{'neg': 0.344, 'neu': 0.656, 'pos': 0.0, 'comp..."
7,1142610028068843520,2019-06-22 21:47:14,NaN,False,False,NaN,0,0,0,This is what the @USMNT has to do to teams th...,/MurphTHEgreat1/status/1142610028068843520,362309349,MurphTHEgreat1,"{'neg': 0.0, 'neu': 0.763, 'pos': 0.237, 'comp..."
8,1142610030803521542,2019-06-22 21:47:14,NaN,False,False,NaN,0,0,0,Pulisic is only 20 and only behind Dempsey and...,/cursive_kid/status/1142610030803521542,148405465,cursive_kid,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
9,1142610033626062851,2019-06-22 21:47:15,NaN,False,False,NaN,3,0,0,5 isn't enough keep it going #USMNT pic.twit...,/justin__darnell/status/1142610033626062851,2890360388,justin__darnell,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."

In [21]:
#keeping this syntax in case we need it for anything later 
#but it actually prevents the split-and-merge technique (used a bit later) from working
#that's because that technique works only on a list, and taking out the braces makes it not be a list any more

#strip off the last character } since it breaks the splitter
#df['polarity'] = df['polarity'].map(lambda x: str(x)[:-1])

In [22]:
#df.polarity.apply(pd.Series) #just doing this to check that it works and actually splits the columns like we want

In [23]:
#create a series from the list within the polarity column and append the series to the main dataframe



df2=df.polarity.apply(pd.Series) \
    .merge(df, left_index = True, right_index = True)

In [24]:
df2.head()

,neg,neu,pos,compound,ID,datetime,has_media,is_reply,is_retweet,medias,nbr_favorite,nbr_reply,nbr_retweet,tweet,url,user_id,usernameTweet,polarity
0,0.000,0.731,0.269,0.8655,1142610007541915648,2019-06-22 21:47:09,NaN,False,False,NaN,4,1,0,The US men are playing like women tonight! Can...,/LeBradyJames/status/1142610007541915648,282399290,LeBradyJames,"{'neg': 0.0, 'neu': 0.731, 'pos': 0.269, 'comp..."
1,0.000,1.000,0.000,0.0000,1142610008468860929,2019-06-22 21:47:09,NaN,False,False,NaN,0,0,0,Cannon on for Lima. #USMNT,/UncSamSoccerPod/status/1142610008468860929,877049725958193152,UncSamSoccerPod,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
2,0.291,0.596,0.112,-0.6249,1142610009915908097,2019-06-22 21:47:09,NaN,True,False,NaN,0,1,0,Remember when people were freaking out about u...,/TUpdike15/status/1142610009915908097,424775138,TUpdike15,"{'neg': 0.291, 'neu': 0.596, 'pos': 0.112, 'co..."
3,0.000,1.000,0.000,0.0000,1142610014005157888,2019-06-22 21:47:10,NaN,True,False,NaN,4,0,1,Where was this during world cup qualifications?,/hongtkwan/status/1142610014005157888,2302603976,hongtkwan,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
4,0.067,0.933,0.000,-0.0572,1142610014412185600,2019-06-22 21:47:10,NaN,True,False,NaN,34,1,1,There is never an excuse for any USMNT to ev...,/ussoccerfeed/status/1142610014412185600,2551822934,ussoccerfeed,"{'neg': 0.067, 'neu': 0.933, 'pos': 0.0, 'comp..."

In [25]:
df2.rename(columns={'text':'tweet', 'compound':'compound_score'}, inplace=True)
df2.head()

,neg,neu,pos,compound_score,ID,datetime,has_media,is_reply,is_retweet,medias,nbr_favorite,nbr_reply,nbr_retweet,tweet,url,user_id,usernameTweet,polarity
0,0.000,0.731,0.269,0.8655,1142610007541915648,2019-06-22 21:47:09,NaN,False,False,NaN,4,1,0,The US men are playing like women tonight! Can...,/LeBradyJames/status/1142610007541915648,282399290,LeBradyJames,"{'neg': 0.0, 'neu': 0.731, 'pos': 0.269, 'comp..."
1,0.000,1.000,0.000,0.0000,1142610008468860929,2019-06-22 21:47:09,NaN,False,False,NaN,0,0,0,Cannon on for Lima. #USMNT,/UncSamSoccerPod/status/1142610008468860929,877049725958193152,UncSamSoccerPod,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
2,0.291,0.596,0.112,-0.6249,1142610009915908097,2019-06-22 21:47:09,NaN,True,False,NaN,0,1,0,Remember when people were freaking out about u...,/TUpdike15/status/1142610009915908097,424775138,TUpdike15,"{'neg': 0.291, 'neu': 0.596, 'pos': 0.112, 'co..."
3,0.000,1.000,0.000,0.0000,1142610014005157888,2019-06-22 21:47:10,NaN,True,False,NaN,4,0,1,Where was this during world cup qualifications?,/hongtkwan/status/1142610014005157888,2302603976,hongtkwan,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
4,0.067,0.933,0.000,-0.0572,1142610014412185600,2019-06-22 21:47:10,NaN,True,False,NaN,34,1,1,There is never an excuse for any USMNT to ev...,/ussoccerfeed/status/1142610014412185600,2551822934,ussoccerfeed,"{'neg': 0.067, 'neu': 0.933, 'pos': 0.0, 'comp..."

In [26]:
df2.compound_score.unique()  #view the range of unique values in the compound_score, so we can make the right labels

array([ 0.8655,  0.    , -0.6249, ...,  0.8363, -0.4983, -0.8006])

In [27]:
#define the process for marking the tweet score
#basically we are checking the value of the compound_score column and returning another value

def label_mark (row):
    
 
    if  row['compound_score']<=-0.6 :
        return '1'
   
    if  row['compound_score']<=-0.2 :
        return '2'
    if  row['compound_score']<=0.19 :
          return '3'
    if  row['compound_score']<=0.59 :
          return '4' 
       
    if  row['compound_score']>=0.591 :
          return '5'

  
    

#df = df[(df['closing_price']>=99 ) & (df['closing_price']<=101)]

In [28]:
df2.apply (lambda row: label_mark(row), axis=1) #this is just to display what the labels will be, should we choose to assign them

0        5
1        3
2        1
3        3
4        3
5        3
6        1
7        5
8        3
9        3
10       3
11       3
12       5
13       3
14       5
15       3
16       4
17       4
18       5
19       3
20       3
21       3
22       5
23       3
24       3
25       5
26       2
27       5
28       3
29       3
        ..
40782    4
40783    5
40784    3
40785    3
40786    4
40787    3
40788    1
40789    4
40790    5
40791    3
40792    3
40793    3
40794    3
40795    3
40796    2
40797    3
40798    4
40799    3
40800    3
40801    3
40802    5
40803    4
40804    2
40805    5
40806    4
40807    3
40808    5
40809    3
40810    3
40811    3
Length: 40812, dtype: object

In [29]:
df2['tweet_grade'] = df2.apply (lambda row: label_mark(row), axis=1) #this assigns the labels into a new column

In [30]:
df2.tweet_grade.unique() #here we are checking to make sure there are no un-graded items and no unused values

array(['5', '3', '1', '4', '2', None], dtype=object)

In [31]:
df2.to_csv('USMNT_Graded_tweets_Part_2.csv', index=True)

In [32]:
#df2['datetime'] =  pd.to_numeric(df2['datetime'])
df2.dtypes

neg               float64
neu               float64
pos               float64
compound_score    float64
ID                 object
datetime           object
has_media          object
is_reply             bool
is_retweet           bool
medias             object
nbr_favorite        int64
nbr_reply           int64
nbr_retweet         int64
tweet              object
url                object
user_id            object
usernameTweet      object
polarity           object
tweet_grade        object
dtype: object

In [33]:
df2['datetime']= pd.to_datetime(df2['datetime']) 

df2['shortdate'] = df2['datetime'].dt.date
df2['shortdate'] = df2['shortdate'].astype(str)
df2['stringdate'] = df2['shortdate'].astype(str)


df2.head()

,neg,neu,pos,compound_score,ID,datetime,has_media,is_reply,is_retweet,medias,...,nbr_reply,nbr_retweet,tweet,url,user_id,usernameTweet,polarity,tweet_grade,shortdate,stringdate
0,0.000,0.731,0.269,0.8655,1142610007541915648,2019-06-22 21:47:09,NaN,False,False,NaN,...,1,0,The US men are playing like women tonight! Can...,/LeBradyJames/status/1142610007541915648,282399290,LeBradyJames,"{'neg': 0.0, 'neu': 0.731, 'pos': 0.269, 'comp...",5,2019-06-22,2019-06-22
1,0.000,1.000,0.000,0.0000,1142610008468860929,2019-06-22 21:47:09,NaN,False,False,NaN,...,0,0,Cannon on for Lima. #USMNT,/UncSamSoccerPod/status/1142610008468860929,877049725958193152,UncSamSoccerPod,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",3,2019-06-22,2019-06-22
2,0.291,0.596,0.112,-0.6249,1142610009915908097,2019-06-22 21:47:09,NaN,True,False,NaN,...,1,0,Remember when people were freaking out about u...,/TUpdike15/status/1142610009915908097,424775138,TUpdike15,"{'neg': 0.291, 'neu': 0.596, 'pos': 0.112, 'co...",1,2019-06-22,2019-06-22
3,0.000,1.000,0.000,0.0000,1142610014005157888,2019-06-22 21:47:10,NaN,True,False,NaN,...,0,1,Where was this during world cup qualifications?,/hongtkwan/status/1142610014005157888,2302603976,hongtkwan,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",3,2019-06-22,2019-06-22
4,0.067,0.933,0.000,-0.0572,1142610014412185600,2019-06-22 21:47:10,NaN,True,False,NaN,...,1,1,There is never an excuse for any USMNT to ev...,/ussoccerfeed/status/1142610014412185600,2551822934,ussoccerfeed,"{'neg': 0.067, 'neu': 0.933, 'pos': 0.0, 'comp...",3,2019-06-22,2019-06-22

In [34]:
#groups = df2.groupby('compound_score').agg['count']
 
#groups=df2.['shortdate', 'compound_score'].groupby(['shortdate', 'compound_score']).agg(['count'])

groups_df=pd.DataFrame(df2.groupby(['shortdate','stringdate', 'tweet_grade']).size().reset_index(name='tweet'))

In [35]:
groups_df.head()

    shortdate  stringdate tweet_grade  tweet
0  2019-06-22  2019-06-22           1    106
1  2019-06-22  2019-06-22           2    363
2  2019-06-22  2019-06-22           3   1381
3  2019-06-22  2019-06-22           4    819
4  2019-06-22  2019-06-22           5    899

In [36]:
groups_df.to_csv('USMNT_Graded_Grouped_final.csv', index=True)